#!/bin/bash
#1
awk -F: '{ print "user",$1,"has id", $3 }' /etc/passwd > work3.log

#2
chage -l root | grep "Last password change" | awk '{print $5, $6, $7}' >> work3.log

#3
getent group | cut -d : -f1 |sed -z 's/\n/,/g;s/,$/\n/' >> work3.log

#4
echo "Be careful!" > /etc/skel/readme.txt

#5
useradd -p 12345678 u1

#6
groupadd g1

#7
usermod -a -G g1 u1

#8
echo user >> work3.log
cat /etc/passwd | grep "u1" | awk 'BEGIN{FS=":"} {print $1, $3}' >> work3.log
echo groups >> work3.log
cat /etc/group | grep "u1" | awk 'BEGIN{FS=":"} {print $1, $3}' >> work3.log

#9
usermod -a -G g1 root

#10
cat /etc/group | grep "g1" | awk 'BEGIN{FS=":"} {print $1, $3}' >> work3.log

#11
usermod --shell /usr/bin/mc u1

#12
useradd -p 87654321 u2

#13
mkdir /home/test13
cp work3.log /home/test13/work3-1.log
cp work3.log /home/test13/work3-2.log

#14
usermod -a -G g1 u2
chown -R u1 /home/test13
chgrp -R g1 /home/test13
chmod 750 /home/test13
chmod 660 /home/test13/*

#15
mkdir /home/test14
chown u1 /home/test14
chmod 1777 /home/test14

#16
cp /usr/bin/nano /home/test14
chmod u+s /home/test14/nano

#17
mkdir /home/test15
echo "Secret" > /home/test15/secret_file
chmod a-r /home/test15
